services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile.dev
    working_dir: /var/www/html/api
    command: php artisan serve --host=0.0.0.0 --port=8080
    env_file: ./.env
    ports:
      - 9000:9000
      - 8080:8080
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - keycloak
    networks:
      - api_db
      - api_keycloak

  node:
    build:
      context: .
      dockerfile: ./node/Dockerfile.dev
    env_file: ./.env
    working_dir: /var/www/html/client
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api_db

  keycloak:
    image: keycloak/keycloak:26.2.5
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/:/opt/keycloak/data/import
    networks:
      - api_keycloak

volumes:
  mysql_data:

networks:
  api_db:
  api_keycloak:
  keycloak_db: