# Etapa 1: Build da aplicação PHP
FROM php:8.3-fpm

# Define diretório da aplicação
WORKDIR /var/www/html/api

# Instalações essenciais e dependências do sistema
RUN apt-get update && apt-get install -y \
    git unzip libzip-dev zip libpng-dev libonig-dev libxml2-dev \
    && docker-php-ext-install zip pdo pdo_mysql mbstring exif pcntl bcmath \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Instala Composer globalmente
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Copia os arquivos da aplicação
COPY ./api .

RUN composer install --no-interaction --optimize-autoloader --no-dev

# SonarScanner CLI
RUN apt-get update && apt-get install -y openjdk-17-jre wget unzip \
  && wget -O /tmp/sonarscanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip \
  && unzip /tmp/sonarscanner.zip -d /opt/ \
  && ln -s /opt/sonar-scanner-*/bin/sonar-scanner /usr/local/bin/sonar-scanner

# Expõe a porta padrão do PHP-FPM
EXPOSE 9000

# Comando padrão do container
CMD ["php-fpm"]