# Etapa 1: Build da aplicação PHP
FROM php:8.3-fpm

# Define diretório da aplicação
WORKDIR /var/www/html

# Instalações essenciais e dependências do sistema
RUN apt-get update && apt-get install -y \
    git unzip libzip-dev zip libpng-dev libonig-dev libxml2-dev \
    && docker-php-ext-install zip pdo pdo_mysql mbstring exif pcntl bcmath \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Instala Composer globalmente
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Copia os arquivos da aplicação
COPY . .

# Instala as dependências da aplicação
#RUN composer install --no-interaction --optimize-autoloader --no-dev

# Expõe a porta padrão do PHP-FPM
EXPOSE 9000

# Comando padrão do container
CMD ["php-fpm"]